### ISSUE TITLE
Emulator won't load

### ISSUE THREAD

**Issue by shinikatx** [winappkits/XPlatformCloudKit#44]
Hi I am completing these labs for a class and I am not able to get the Phone 8 Emulator to load, multiple errors. 

I upgraded my pc to Win 8.1 Pro, I used Visual Studio 2013. Everything loads but the droid like you said. I retargeted the solution to 8.1. but getting invalid query when the emulator tries to load. I unistalled 2013 and installed VS 2012 with all the updates plus the Phone8 SDK but when I try to load the solution it won't load Phone 8. One of the errors I'm getting is about a Microsoft.Bcl.Build. I now have both VS 2012 and 2013 installed. I keep getting Invalid Query error box on Windows Phone Emulator window. Please help. shinika@msn.com, elders@uhv.edu, 713-702-7088

**Comment by toolboc** [comment]
@shinikatx , Please see http://msdn.microsoft.com/en-us/library/windows/apps/ff626524(v=vs.105).aspx 

This is likely a system issue and not an issue with the XPCK codebase.
